### ISSUE TITLE
data-autocomplete-query-param-value not working

### ISSUE THREAD

**Issue by kg-currenxie** [afcapel/stimulus-autocomplete#128] opened 2023-01-03 14:43 UTC
```
<div data-controller="autocomplete" data-autocomplete-url-value="/search" data-autocomplete-query-param-value="query" role="combobox">
```

still gives me `?q=` in the url

```
pin 'stimulus-autocomplete', to: 'https://ga.jspm.io/npm:stimulus-autocomplete@3.0.2/src/autocomplete.js'
pin '@hotwired/stimulus', to: 'https://ga.jspm.io/npm:@hotwired/stimulus@3.2.1/dist/stimulus.js'
```

**Comment by robinaugh** [comment] 2023-02-15 21:20
@kg-currenxie I ran into this issue too - it looks like the latest release does not yet include this functionality, but changing my `package.json` to point at the current SHA of the `main` branch (and then `yarn install`ing) did the trick:

```
git+https://github.com/afcapel/stimulus-autocomplete.git#7c22de1eff4b1028ea4918db60c63f6b30f04b8c
```

**Comment by kg-currenxie** [comment] 2023-02-16 02:01
I see, thanks :D Hope it gets released soon

**Comment by ACPK** [comment] 2023-02-28 19:44
@kg-currenxie Duplicate of https://github.com/afcapel/stimulus-autocomplete/issues/128

**Comment by afcapel** [comment] 2023-03-01 17:21
I've just published a new release that includes this feature.

**Closed by afcapel** 2023-03-01 17:21 UTC
